apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datenna-openbao
  namespace: datenna-demo
spec:
  provider: openbao
  parameters:
    roleName: datenna-app
    audience: openbao
    objects: |
      - objectName: postgres-username
        secretPath: database/creds/datenna-app
        secretKey: username
        filePermission: 0444
      - objectName: postgres-password
        secretPath: database/creds/datenna-app
        secretKey: password
        filePermission: 0444
      - objectName: minio-access-key
        secretPath: kv/data/minio/datenna-app-active
        secretKey: access-key
        filePermission: 0444
      - objectName: minio-secret-key
        secretPath: kv/data/minio/datenna-app-active
        secretKey: secret-key
        filePermission: 0444
