injector:
  enabled: false

server:
  podManagementPolicy: Parallel
  affinity: ""
  authDelegator:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi
  dataStorage:
    enabled: true
    size: 512Mi
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true

csi:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 192Mi
  agent:
    enabled: true
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 192Mi
